plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'com.vanniktech.maven.publish' version '0.37.0'
}

version = '2.8.1'
group = 'meldexun.asmutil'
base.archivesName = 'asmutil'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'org.ow2.asm:asm:6.2'
    compileOnly 'org.ow2.asm:asm-tree:6.2'
    compileOnly 'org.apache.logging.log4j:log4j-api:2.15.0'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.15.0'
}

jar {
    from('LICENSE') {
        rename { 'META-INF/' + it }
    }

    manifest.attributes([
        'Built-By': 'Meldexun',
        'Specification-Title': 'ASMUtil',
        'Specification-Version': '2.8',
        'Specification-Vendor': 'Meldexun',
        'Implementation-Title': 'ASMUtil',
        'Implementation-Version': version,
        'Implementation-Vendor': 'Meldexun',
        'Implementation-Timestamp': new Date().format('yyyy-MM-dd HH:mm:ss')
    ])
}

mavenPublishing {
    coordinates('io.github.meldexun', 'asmutil', version)

    pom {
        name = 'ASMUtil'
        description = 'ASM utility primarily designed for Minecraft modding.'
        inceptionYear = '2021'
        url = 'https://github.com/Meldexun/ASMUtil'
        licenses {
            license {
                name = 'The MIT License'
                url = 'https://opensource.org/license/mit'
                distribution = 'https://opensource.org/license/mit'
            }
        }
        developers {
            developer {
                id = 'meldexun'
                name = 'Meldexun'
                url = 'https://github.com/Meldexun'
            }
        }
        scm {
            url = 'https://github.com/Meldexun/ASMUtil'
            connection = 'scm:git:git://github.com/Meldexun/ASMUtil.git'
            developerConnection = 'scm:git:ssh://git@github.com/Meldexun/ASMUtil.git'
        }
    }

    publishToMavenCentral()
    signAllPublications()
}
